---
layout: Resume
title: Henry Gao's Resume
---
# Henry Gao
Economics and Data Science student at BYUI

<div id="webaddress">
<a href="https://www.linkedin.com/in/henry-gao229/">My linkedin profile</a>
</div>


## Currently

Studying at BYUI as full time student, actively looking for internships related to economics, finance or data science

### Specialized in

Statistics, Data Science, Economics, Finance, Investment, AI Algorithms


### Research interests

AI algorithm, automatic trading algorithm, quantitative trading.


## Education

`2020-2023`
__Communication University of Zhejiang__

- GPA:3.7/4.0.
- Majoring in Software Engineering

`2023 - 2023`
__University of California Santa Barbara__

- GPA:3.67/4.0.
- Majoring in Software Engineering

`2023 - now`
__Brigham Young University - Idaho__

- GPA:4.0/4.0.
- Majoring in Economics and minoring in Data Science

## Technical Skills

__SQL__:Compiled a simulated stock trading website, deploy mysql database storage 
stock data and can complete various functions such as storage, calling, querying, 
updating data.

__Python__: Feed a large number of credit data samples to the deep neural network for 
training, and then use the trained model to test the test set, and calculate whether the 
customer should be given a loan based on the customer's credit data.

__Excel__: Can skillfully operate excel tables to calculate the consumer index and 
inflation rate of local residents, and generate charts based on the data.

__MS Suite__: As a college student who has many years of experience, familiar with MS 
Suite and has used PPT in American middle school to perform cultural display.

## Job Experiences

`April 2024 - Present`
__Microeconomic Teaching Assistant__

- Assist professors weekly in producing teaching PPTs and provide suggestions and technical support.
- Meet with students weekly in office hours to answer questions about grades and microeconomic concepts. Improve 80 students' learning performance by giving easy-to-understand explanations and providing study suggestions
- Solve 80 students' problems related to exams, assignments and quizzes at any time according to the professor's requirements
- Help professors analyze and identify student problems and change course structures and settings to improve teaching quality

<!-- ### Footer

Last updated: October 2024 -->